# preload = /home/potato/Pictures/wallpaper1.jpg
# preload = /home/potato/Pictures/wallpaper2.jpg
# wallpaper = eDP-1,/home/potato/Pictures/wallpaper1.jpg
# wallpaper = HDMI-A-1,/home/potato/Pictures/wallpaper2.jpg
wallpaper { 
  monitor = eDP-1
  path = ~/Pictures/wallpaper1.jpg
  fit_mode = cover
}

wallpaper { 
  monitor = HDMI-A-1
  path = ~/Pictures/wallpaper2.jpg
  fit_mode = cover
}


wallpaper { 
  monitor = DP-3
  path = ~/Pictures/wallpaper2.jpg
  fit_mode = cover
}

#if more than one preload is desired then continue to preload other backgrounds
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
#if more than one monitor in use, can load a 2nd image
# .. more monitors

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off


